### ISSUE TITLE
No await in loop is missing documentation

### ISSUE THREAD

**Issue by RDambrosio016** [RDambrosio016/RSLint#1]
`no-await-in-loop` is missing documentation.

To add documentation, place doc comments inside of the `declare_lint!` call in the [source](https://github.com/RDambrosio016/RSLint/blob/dev/rslint_core/src/groups/errors/no_await_in_loop.rs), before the struct name, then use `cargo docgen` to generate appropriate user facing documentation. Js code blocks should use `ignore` instead of `js`, this is to have basic highlighting in rustdoc, however, we may change it in the future. The docgen will automatically change these to `js`. Moreover, make sure the docs have an initial one sentence description with two newlines (you can see other rule docs for an example).

**Comment by magurotuna** [comment]
Hi @RDambrosio016 ;)
I have been contributing to deno_lint, mainly implementing some rules. (actually I wrote `no-await-in-loop` in deno_lint!)
I read your blog post a few days ago and I got really interested in RSLint architecture, because sometimes I feel like it's pretty difficult to implement rules in deno_lint due to the limitation of AST-based way. 
So I would like to learn how RSLint is implemented deeply. This issue looks nice for my first step :smile:  May I work on it?

**Comment by RDambrosio016** [comment]
@magurotuna go ahead! if you have any questions feel free to ask, i am also on the rust community discord regularly. I reccomend running `cargo doc` on the project then looking at the docs of each crate, the main things you will need for knowing how to implement rules are the rowan SyntaxNode/SyntaxToken docs and the rslint_parser util and ast docs 🙂, make sure to check out docs/dev too.

**Comment by magurotuna** [comment]
Thanks for the quick reply and very detailed advice @RDambrosio016 !
I'll read those docs, which will definitely help me understand RSLint. Then I will add for `no-await-in-loop`.
